# -*- coding: utf-8 -*-
# Batch data for ToolForge sprint (2026-07-15) — all slugs verified MISSING.

TOOLS = [
 dict(slug="slack", name="Slack", tagline="The AI-powered work hub where teams message, meet, and automate - now with Slack AI built in.",
   category="Productivity", color1="#4A154B", color2="#611f69", initials="Sl", price="$7.25/mo", price_label="Pro plan",
   price_num="7.25", free_tier="Free tier (90-day history)", rating="4.7/5", rating_num="4.7", users="50M+ daily users", founded="2013",
   headline="Where work happens, now with AI",
   intro="Slack is the messaging platform that replaced email for millions of teams. In 2024-2025 it added Slack AI - thread summaries, search answers, and huddle recaps - plus deep automation via Workflow Builder and 2,600+ app integrations.",
   who_for="Teams of any size that live in chat, run standups in channels, and want AI summaries without leaving the app.",
   features=[("💬","Channels & Huddles","Organize work by topic, then spin up instant voice huddles without a meeting link."),
             ("🤖","Slack AI","Summarize long threads, get answers from your workspace history, and recap huddles automatically."),
             ("🔗","2,600+ apps","Connect GitHub, Salesforce, Google Drive, and your whole stack in one place."),
             ("⚡","Workflow Builder","No-code automations that route approvals, ticketing, and alerts without code.")],
   pros=["Best-in-class search and integrations","Slack AI summaries save real time","Free tier is generous for small teams","Huddles beat Zoom for quick syncs"],
   cons=["Can get noisy without channel hygiene","Per-seat pricing adds up fast","Slack AI is a paid add-on","Heavy RAM usage on desktop"],
   verdict="If your team already lives in chat, Slack with AI is the obvious pick. The $7.25/mo Pro (plus the AI add-on) pays for itself the first week you stop digging through threads.",
   cta_url="https://slack.com/"),

 dict(slug="discord", name="Discord", tagline="The community platform that beat Slack for communities, gaming, and creator fan clubs - now with Clyde AI.",
   category="Productivity", color1="#5865F2", color2="#4752C4", initials="Di", price="Free", price_label="Basic (Nitro $9.99/mo)",
   price_num="0", free_tier="Free (voice, text, bots)", rating="4.6/5", rating_num="4.6", users="150M+ MAU", founded="2015",
   headline="Build a community that actually sticks",
   intro="Discord started as a gamer hangout and became the default home for creators, DAOs, and fan communities. Server roles, bots, and Clyde AI (auto-moderation, conversation summaries) make it scale from 10 to 100,000 members.",
   who_for="Creators, community builders, and gaming teams who need voice, text, and bots in one free space.",
   features=[("🎙️","Voice & Stage channels","Crystal-clear voice, screen share, and staged events for town halls."),
             ("🤖","Clyde AI + bots","AI moderation, thread summaries, and 100,000+ community bots for automation."),
             ("🛡️","Roles & permissions","Granular control so your community scales without chaos."),
             ("📱","Cross-platform","Native apps on every OS; works great on mobile.")],
   pros=["Free forever for most communities","Best-in-class voice quality","Bot ecosystem is unmatched","Roles scale to 100k+ members"],
   cons=["Not built for corporate docs/workflow","Search is weak on free tier","Notification overload is possible","Clyde AI still rolling out"],
   verdict="For communities and creators, Discord is untouchable and free. If you run a paid product team, pair it with Slack - but for fan clubs and DAOs, Discord wins.",
   cta_url="https://discord.com/"),

 dict(slug="notion", name="Notion", tagline="The connected workspace - docs, wikis, projects, and now Notion AI that writes and searches for you.",
   category="Productivity", color1="#000000", color2="#37352F", initials="No", price="$10/mo", price_label="Plus plan",
   price_num="10", free_tier="Free (personal)", rating="4.7/5", rating_num="4.7", users="100M+ users", founded="2016",
   headline="One workspace to replace them all",
   intro="Notion is the all-in-one doc, wiki, and project tool. Notion AI (Q&A across your workspace, writing, and translation) turned it from a note app into a true second brain for teams.",
   who_for="Knowledge workers, startups, and teams who want docs plus tasks plus a wiki in one flexible block system.",
   features=[("📝","Blocks & databases","Every page is composable - tables, boards, calendars, and docs in one."),
             ("🤖","Notion AI","Ask questions across your workspace, draft docs, and auto-summarize meetings."),
             ("🔗","Templates & sync","Thousands of community templates plus synced blocks across pages."),
             ("🌐","Publish & sites","Turn any page into a public site or help center in a click.")],
   pros=["Incredibly flexible block system","Notion AI Q&A is genuinely useful","Free tier covers most personal use","Great template ecosystem"],
   cons=["Can become a messy second brain without structure","Offline mode is limited","AI is a paid add-on","Learning curve for databases"],
   verdict="Notion is the default workspace for solo workers and small teams. At $10/mo Plus plus AI it replaces three separate subscriptions. Power users graduate to ClickUp for heavier project management.",
   cta_url="https://www.notion.so/"),

 dict(slug="clickup", name="ClickUp", tagline="The one app to replace them all for project management - tasks, docs, goals, and ClickUp Brain AI.",
   category="Productivity", color1="#7B68EE", color2="#5B4BD6", initials="Cl", price="$10/mo", price_label="Business plan",
   price_num="10", free_tier="Free (100MB)", rating="4.5/5", rating_num="4.5", users="10M+ users", founded="2017",
   headline="Project management with an AI brain",
   intro="ClickUp crams docs, tasks, whiteboards, goals, and time tracking into one app. ClickUp Brain adds AI that summarizes work, writes updates, and answers what is blocking the launch across your workspace.",
   who_for="Operations leads, agencies, and teams juggling many projects who want one source of truth.",
   features=[("✅","Tasks & views","List, board, Gantt, calendar, and box views for any workflow."),
             ("🧠","ClickUp Brain","AI that summarizes tasks, drafts status updates, and answers workspace questions."),
             ("🎯","Goals & docs","OKRs, docs, and whiteboards live next to your tasks."),
             ("⏱️","Time tracking","Built-in timers and workload view without a separate tool.")],
   pros=["Replaces 5+ PM tools","ClickUp Brain AI is powerful","Highly customizable","Free tier is usable"],
   cons=["Feature overload can overwhelm new users","Mobile app is slower","Steep initial setup","Can feel bloated"],
   verdict="If you manage complex projects across many teams, ClickUp beats Notion on pure PM horsepower. The $10/mo Business plan plus Brain is a steal versus Asana plus Jira plus Docs.",
   cta_url="https://clickup.com/"),

 dict(slug="zoom", name="Zoom", tagline="The video meeting standard - now with Zoom AI Companion for summaries, chapters, and live insights.",
   category="Productivity", color1="#2D8CFF", color2="#0B66E4", initials="Zo", price="$13.33/mo", price_label="Pro plan",
   price_num="13.33", free_tier="Free (40-min limit)", rating="4.6/5", rating_num="4.6", users="300M+ daily participants", founded="2011",
   headline="Meetings that summarize themselves",
   intro="Zoom defined remote meetings. AI Companion (free with paid plans) auto-generates meeting summaries, smart chapters, and live follow-ups - no separate note app needed.",
   who_for="Businesses, schools, and anyone running regular video calls who wants built-in AI notes.",
   features=[("🎥","HD meetings","Reliable video with breakout rooms, polls, and whiteboard."),
             ("🤖","AI Companion","Auto summaries, action items, and catch-me-up recaps - free on paid plans."),
             ("📞","Phone & webinar","Zoom Phone and Webinars replace separate comms tools."),
             ("🔒","Security","End-to-end encryption and SOC2 compliance for enterprise.")],
   pros=["Rock-solid reliability","AI Companion is free on paid plans","Whiteboard and breakouts are great","Works on any device"],
   cons=["Free tier capped at 40 min","UI can feel dated","AI needs a paid plan to unlock fully","Zoom fatigue is real"],
   verdict="For pure meeting quality, Zoom still wins. Pair it with AI Companion and you can skip Otter or Fireflies for most calls. Google Meet is the free alternative for Workspace shops.",
   cta_url="https://zoom.us/"),

 dict(slug="canva", name="Canva", tagline="Design anything in minutes - presentations, social posts, and video, now supercharged by Magic Studio AI.",
   category="Image", color1="#00C4CC", color2="#7D2AE8", initials="Ca", price="$15/mo", price_label="Pro plan",
   price_num="15", free_tier="Free (millions of assets)", rating="4.8/5", rating_num="4.8", users="190M+ users", founded="2012",
   headline="Pro design without a designer",
   intro="Canva turned everyone into a designer. Magic Studio adds AI image generation, Magic Write, and one-click resizing across 100+ formats - from Instagram stories to pitch decks.",
   who_for="Marketers, founders, teachers, and creators who need on-brand visuals fast without Photoshop.",
   features=[("🎨","Templates & drag-drop","500k+ templates; resize any design to any platform instantly."),
             ("✨","Magic Studio","Text-to-image, Magic Write, and background removal in one AI suite."),
             ("🎬","Video & Presentations","Edit short videos and build animated decks without leaving Canva."),
             ("👥","Brand kit & teams","Lock brand colors, fonts, and logos for consistent team output.")],
   pros=["Zero learning curve","Magic Studio AI is genuinely fun","Free tier is huge","Brand kits keep teams consistent"],
   cons=["Not a Photoshop replacement for pro retouching","Export limits on free tier","Template sameness can hurt branding","Advanced features behind Pro"],
   verdict="Canva is the fastest path from idea to published visual. At $15/mo Pro it replaces Photoshop for 90% of marketing teams. For AI image generation, pair it with Midjourney.",
   cta_url="https://www.canva.com/"),

 dict(slug="zapier", name="Zapier", tagline="Connect 7,000+ apps with no code - and now Zapier AI builds and fixes your automations for you.",
   category="Productivity", color1="#FF4F00", color2="#E03E00", initials="Za", price="$19.99/mo", price_label="Starter plan",
   price_num="19.99", free_tier="Free (100 tasks/mo)", rating="4.6/5", rating_num="4.6", users="2.2M+ companies", founded="2011",
   headline="Automate the boring 80%",
   intro="Zapier is the no-code glue between every SaaS app. Natural-language Zap building and AI assistants now let you describe a workflow and watch it get wired up - no brittle mapping.",
   who_for="Ops, founders, and marketers who want automations without hiring an engineer or learning n8n.",
   features=[("🔌","7,000+ integrations","Almost any app you use has a Zapier connector."),
             ("🤖","AI by Zapier","Describe a Zap in plain English; AI drafts and fixes the steps."),
             ("⚙️","Multi-step Zaps","Branching logic, filters, and delays across dozens of actions."),
             ("📊","Tables & interfaces","Lightweight databases and forms without a separate tool.")],
   pros=["Largest app library by far","AI Zap builder lowers the floor","Reliable and well-documented","Free tier for light use"],
   cons=["Per-task pricing gets expensive at scale","Slower than code for complex logic","UI lag on big Zaps","Locked to Zapier model"],
   verdict="For no-code automation with zero learning curve, Zapier is the safest bet. At $19.99/mo Starter it pays off the first week you stop copy-pasting. Power users graduate to n8n for self-hosted scale.",
   cta_url="https://zapier.com/"),

 dict(slug="perplexity-ai", name="Perplexity AI", tagline="The AI answer engine - get sourced, cited answers instead of a wall of blue links.",
   category="Research", color1="#20808D", color2="#1A6E78", initials="Pe", price="$20/mo", price_label="Pro plan",
   price_num="20", free_tier="Free (5 Pro queries/4h)", rating="4.6/5", rating_num="4.6", users="15M+ users", founded="2022",
   headline="Search, but it answers",
   intro="Perplexity is the answer engine that cites its sources. Ask a question, get a synthesized response with footnotes you can click. Spaces, file upload, and focus modes make it a research powerhouse.",
   who_for="Researchers, students, and analysts who want trustworthy answers with citations, not just a chatbot.",
   features=[("🔎","Cited answers","Every claim links to a source - no hallucinated facts without a trail."),
             ("📁","Spaces & files","Upload PDFs and build shared research spaces with your team."),
             ("🌐","Focus modes","Toggle Academic, Wolfram, Reddit, or YouTube for targeted results."),
             ("🤖","Pro models","Route hard questions to GPT-4, Claude, or Sonar for deeper reasoning.")],
   pros=["Citations build real trust","Faster than 10-tab Googling","Great for academic research","Clean, ad-free UI"],
   cons=["Not a creative writing tool","Pro query limits on free tier","Sometimes shallow on niche topics","Can lag on breaking news"],
   verdict="For research and just answer my question, Perplexity beats Google and ChatGPT. The $20/mo Pro is worth it if you research daily. For open-ended brainstorming, keep ChatGPT handy.",
   cta_url="https://www.perplexity.ai/"),

 dict(slug="pika-lab", name="Pika", tagline="Turn text and images into short AI videos - Pika 2.0 nails character and scene consistency.",
   category="Video", color1="#7C3AED", color2="#6D28D9", initials="Pi", price="$10/mo", price_label="Standard plan",
   price_num="10", free_tier="Free (daily credits)", rating="4.4/5", rating_num="4.4", users="2M+ creators", founded="2023",
   headline="Make videos from a sentence",
   intro="Pika lets anyone generate and edit short videos from prompts or images. Pika 2.0 added Pikaffects, scene consistency, and lip-sync - making it a favorite for social clips and product teasers.",
   who_for="Creators, marketers, and founders who need scroll-stopping video without a camera or editor.",
   features=[("🎬","Text & image to video","Describe a scene or upload an image; Pika animates it."),
             ("😎","Pikaffects & lip-sync","Fun effects plus sync audio to character mouths."),
             ("🎨","Scene consistency","Keep characters and styles stable across shots."),
             ("✏️","Video editing","Modify regions, extend frames, and restyle existing clips.")],
   pros=["Easiest entry into AI video","Strong style consistency","Fun effects drive shares","Free daily credits"],
   cons=["Short clips only (seconds)","Not cinematic like Sora or Veo yet","Credits burn fast on Pro","Occasional morphing artifacts"],
   verdict="Pika is the best on-ramp to AI video for non-editors. At $10/mo it is cheaper than Runway and more playful. For longer, cinematic output, graduate to Sora or Kling.",
   cta_url="https://pika.art/"),

 dict(slug="databricks", name="Databricks", tagline="The data and AI platform where teams build lakehouses and ship production ML on one stack.",
   category="Business", color1="#FF3621", color2="#E02E18", initials="Db", price="Custom", price_label="Enterprise (usage-based)",
   price_num="0", free_tier="Community tier", rating="4.6/5", rating_num="4.6", users="12,000+ companies", founded="2013",
   headline="One platform for data and AI",
   intro="Databricks unified analytics, the lakehouse, and Mosaic AI let data teams query, train, and serve models without stitching a dozen tools. It is where most enterprises actually run GenAI.",
   who_for="Data engineering and ML teams at scale who need governance, collaboration, and GPU training in one place.",
   features=[("🏞️","Lakehouse","Data warehouse plus data lake in one governed store."),
             ("🤖","Mosaic AI","Fine-tune, evaluate, and deploy models with guardrails."),
             ("📊","Notebooks & Delta","Collaborative notebooks on ACID tables at petabyte scale."),
             ("🔐","Unity Catalog","Central governance, lineage, and access control.")],
   pros=["Industry standard for lakehouses","Great for governed GenAI","Strong partner ecosystem","Scales to petabytes"],
   cons=["Steep learning curve","Cost adds up fast","Overkill for small teams","Vendor lock-in risk"],
   verdict="If you run data plus AI at enterprise scale, Databricks is the safe default. Startups can begin on the Community tier, then scale. For pure warehousing, Snowflake is the lighter alternative.",
   cta_url="https://www.databricks.com/"),

 dict(slug="snowflake", name="Snowflake", tagline="The cloud data warehouse that scales to zero and back - now with Cortex AI for in-warehouse GenAI.",
   category="Business", color1="#29B5E8", color2="#1793C4", initials="Sn", price="Usage-based", price_label="per-second compute",
   price_num="0", free_tier="30-day trial", rating="4.5/5", rating_num="4.5", users="9,000+ customers", founded="2012",
   headline="Data warehousing, reimagined",
   intro="Snowflake separated storage and compute so you pay only for what you use. Snowpark and Cortex AI bring Python and LLMs directly into your warehouse - no data movement.",
   who_for="Data teams who need elastic, secure warehousing and want to run AI on their own data without exports.",
   features=[("❄️","Elastic compute","Scale to thousands of cores and back to zero in seconds."),
             ("🧠","Cortex AI","Run LLMs and vector search inside the warehouse on your data."),
             ("🐍","Snowpark","Build pipelines and ML in Python, Java, or Scala natively."),
             ("🔗","Marketplace","Share and buy live datasets without copying.")],
   pros=["Separates storage and compute (huge cost win)","Cortex keeps AI in-warehouse","Rock-solid security","Marketplace is handy"],
   cons=["Usage billing is hard to predict","Less flexible than a lakehouse for unstructured","Steeper than BigQuery for starters","Needs data eng talent"],
   verdict="For elastic, secure warehousing, Snowflake is best-in-class. Cortex AI lets you run GenAI without leaving your data. Databricks wins if you need a full lakehouse plus training stack.",
   cta_url="https://www.snowflake.com/"),

 dict(slug="vertex", name="Vertex AI", tagline="Google's unified AI platform - train, tune, and deploy Gemini and open models with enterprise guardrails.",
   category="Coding", color1="#4285F4", color2="#1A73E8", initials="Vx", price="Pay-as-you-go", price_label="per-token / per-use",
   price_num="0", free_tier="$300 credits", rating="4.5/5", rating_num="4.5", users="Thousands of enterprises", founded="2021",
   headline="Build on Gemini, safely",
   intro="Vertex AI is Google Cloud's ML platform: one place for foundation models (Gemini), custom training, vector search, and MLOps. Grounding and safety filters make it enterprise-ready.",
   who_for="Engineers and ML teams on Google Cloud who want Gemini plus their own models with governance and MLOps.",
   features=[("🌟","Gemini & models","Access Gemini plus Imagen, Veo, and open weights via one API."),
             ("🎯","Grounding & safety","RAG, citations, and safety filters for production trust."),
             ("🚀","End-to-end MLOps","Training, tuning, evaluation, and deployment in one console."),
             ("🔎","Vector search","Managed embeddings and similarity search at scale.")],
   pros=["Deep Gemini integration","Strong MLOps tooling","Enterprise governance","$300 free credits to start"],
   cons=["Tied to Google Cloud","Console can be complex","Costs climb with scale","Steeper than OpenAI for quick prototypes"],
   verdict="If you are on Google Cloud, Vertex AI is the natural home for Gemini plus your models. For a simpler API-only start, OpenAI or Anthropic beat it. Databricks is the alternative for lakehouse-centric teams.",
   cta_url="https://cloud.google.com/vertex-ai"),
]
